<?php

namespace app\modules\user\controllers;
use app\models\ModuleUser;
use Yii;
use app\models\Article;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function beforeAction($action)
    {
        $thisUser = ModuleUser::findOne(['id'=>\Yii::$app->user->getId()]);
        if ($thisUser->status==1) return Yii::$app->response->redirect('/user/profile/index');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex($active=false,$moder=false)
    {
        $queryFilter = ['author'=>Yii::$app->user->getId()];
        if($active=="ok"&&$moder=="ok") {
        } elseif ($active=="ok") {
            $queryFilter = ['status'=>1,'author'=>Yii::$app->user->getId()];
        } elseif ($moder=="ok") {
            $queryFilter = ['status'=>0,'author'=>Yii::$app->user->getId()];
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Article::find()->with('category')->where($queryFilter),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('index', compact(['dataProvider','active','moder','userName']));
    }
    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $temp = $this->findModel($id);
        if ($temp->author==Yii::$app->user->getId()){
            return $this->render('view', [
                'model' => $temp,
            ]);
        } else return $this->redirect('/user/article');

    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if (is_object($model->imageFile)) {
                $model->imageFile->saveAs('images/article/' . $model->id . '.jpg');
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->author==Yii::$app->user->getId()){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {

                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                if (is_object($model->imageFile)) {
                    $model->imageFile->saveAs('images/article/' . $model->id . '.jpg');
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
            return $this->render('update', [
                'model' => $model,
            ]);
        } else return $this->redirect('/user/article');





    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {


        $temp = $this->findModel($id);
        if ($temp->author==Yii::$app->user->getId()){
            $this->findModel($id)->delete();

            return $this->redirect(['index']);
        } else return $this->redirect('/user/article');

    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
